#!/bin/bash
PKG=~/oss-tool/node/dismc/startmc.js

CMD=`node $PKG $*`
if [[ "$?" == "0" ]]; then
	if [[ $CMD == "sudo "* ]]; then
		echo "Run: " $CMD
		$CMD 
	else
		echo "Run: " $CMD
		$CMD >> /dev/null 2>&1 &
	fi
else
	echo $CMD
fi
