#!/bin/bash
PKG=~/oss-tool/node/dismc/stopmc.js
LOG=~/HOME/log/stopmc.log

echo `date` " stopmc $*" >> $LOG

function kill_pid
{
	PID=`ps -ef | grep -e $1 | grep -v grep | awk '{print $2}'`
	if [[ $PID == "" ]]; then 
		echo "Program not found"
	else
		echo "Kill PID $PID "
		kill $PID
	fi
}

function stop_proc
{
	CMD=`node $PKG $*`
	if [[ $CMD == "Error:"* ]]; then
		echo $CMD
		echo $CMD >> $LOG
	else
		echo "Run: " $CMD
		echo "Run: " $CMD >> $LOG
		$CMD 
	fi
}

if [[ "$1" == "-a" ]]; then
	for proc in `dismc -l`
	do
		stop_proc -b $proc
	done
elif [[ "$1" == "-r" ]]; then
	stopmc -b $2
	sleep 1
	startmc -b $2
else
	stop_proc $*
fi


